from src.config import settings

EPSS_API_URL = settings.EPSS_API_URL
EPSS_OFFLINE_CSV_PATH = settings.EPSS_OFFLINE_CSV_PATH
EPSS_USE_OFFLINE = settings.EPSS_USE_OFFLINE
EPSS_BATCH_SIZE = 100
EPSS_REQUEST_TIMEOUT = 30
EPSS_CSV_CVE_COLUMN = "cve"
EPSS_CSV_SCORE_COLUMN = "epss"
EPSS_CSV_PERCENTILE_COLUMN = "percentile"
DEFAULT_EPSS_SCORE = 0.0
DEFAULT_EPSS_PERCENTILE = 0.0
EPSS_CACHE_TTL = 86400
